### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by timobrembeck**
A few small cleanups including:

- Add debug logging
- Remove unused imports
- Use f-strings instead of %-formatters

### CODE REVIEW

**Comment by timobrembeck** [comment]
@claudep what do you think about adding automated tools to ensure the code quality in the long term? If you're open to this idea, which ones would you prefer (black, flake8, pylint, isort, etc.)?

**Comment by claudep** [comment]
For me, isort and flake8 are fine, however I don't like black at all, as it forces you to a unique formatting way which I find sometimes not very readable.

**Comment by claudep** [comment]
Moving to f-strings is generally K, however note that gettext currently doesn't support translation of f-strings. So at least for message in management commands, if your plans includes their message translations, avoid using f-strings for those messages.

**Comment by timobrembeck** [comment]
> however note that gettext currently doesn't support translation of f-strings. So at least for message in management commands, if your plans includes their message translations, avoid using f-strings for those messages.

Alright, removed them from the management commands.

**Pull request merged**
