### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
More or less required if we want to support Django 3.0.

**Comment by claudep** [comment]
@andybak @fruitschen, any opinion on this?

**Comment by andybak** [comment]
I think that's fine for us as long as there's a tag or branch for legacy sites.

@fruitschen FYI...

**Comment by claudep** [comment]
The `1.6` release is tagged, and if we need to make that code evolve, we can always create a `1.6.x` branch for that.

**Pull request merged**
