### PR TITLE
Add `flake8`

### PR DESCRIPTION
**Pull request by timobrembeck**
I realize this mostly comes down to personal preference, so feel free to reject any of these changes :smile: 

I experimented a bit with other formatters ([autopep8](https://github.com/hhatto/autopep8) & [yapf](https://github.com/google/yapf)), but I wasn't satisfied with the results... I ended up formatting the code with black nevertheless and reverted any line breaks which didn't improve readability in my opinion...

Sorry for the large diff, mostly these are changes from single quotes to double quotes (which I do not generally prefer, I just wanted the quotes to be consistent, and I did not find a tool which behaves similar to black in that way but uses single quotes instead of double quotes)...

### CODE REVIEW

**Comment by claudep** [comment]
Disclaimer: I'm not the maintainer of this package, only an approved committer, so my opinion is only consultative.

While flake8 and isort can bring real improvements to code, I don't like the added standardization of black, which adds very little value to my eyes when you already have flake8-compatible code.

**Comment by claudep** [comment]
Forgot the first sentence of my previous comment, I thought I was on another package, sorry!

But I stand by the second part of my comment.

**Comment by timobrembeck** [comment]
> I don't like the added standardization of black, which adds very little value to my eyes when you already have flake8-compatible code.

Well, the code wasn't flake8-compatible before and black reduced the number of warnings considerably, but I now removed the formatting commit and manually fixed all remaining issues flake8 found.

The main two advantages I see:
1. Flake only complains about things, it does not fix them. Fixing warnings is a very tedious task, I see no reason to invest time and energy in doing things manually if there is a tool which can do them automatically for you
2. I didn't like the inconsistent usage of single and double quotes which flake8 is fine with

But as I already stated, I'm fine with complying to your preferences here :smile:

**Comment by timobrembeck** [comment]
And by the way, thanks a lot for the quick response times and tons of reviews over the last few days :smiley:

**Comment by claudep** [comment]
It's a rather big PR with multiple different things to review. Do you think it wouldn't take you too much time to separate it in more reviewable PRs?

**Pull request merged**
