### PR TITLE
Updated CHANGELOG for the 1.4 release

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@andybak I'd like to have a release soon, is it OK for you? Can you quickly review my changelog proposal to see if I missed major stuff (and check the language, too!).

**Comment by andybak** [comment]
That all looks good to me. There were a few bug fixes not mentioned in the readme but I'm OK with not mentioning every single fix.

**Comment by claudep** [comment]
Thanks, I'll take care of the release then, unless you plan to do it.

**Comment by andybak** [comment]
That would be great. No time right now but I'd love you to walk me through the next one so I can stop leaving it to you each time. I know the rough gist - I'm just not sure I wouldn't miss a small detail.

**Comment by claudep** [comment]
Nothing magic... `python setup.py sdist` to make the tar.gz, then `twine upload dist/django-linkcheck-1.4.tar.gz` to upload to PyPI. Done!

**Pull request merged**
